# Generated by Django 5.2.17 on 2026-09-12 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='智能体名称')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='标识')),
                ('avatar', models.CharField(blank=True, max_length=255, verbose_name='头像')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('welcome_message', models.CharField(default='您好，我是物联网学科智能助手', max_length=255, verbose_name='欢迎语')),
                ('suggested_questions', models.JSONField(blank=True, default=list, verbose_name='推荐问题')),
                ('system_prompt', models.TextField(blank=True, verbose_name='系统提示词')),
                ('top_k', models.IntegerField(default=5, verbose_name='召回条数')),
                ('score_threshold', models.FloatField(default=0.0, verbose_name='相似度阈值')),
                ('temperature', models.FloatField(default=0.3, verbose_name='温度')),
                ('retrieval_first', models.BooleanField(default=True, help_text='开启后严格基于检索结果作答，关闭则允许模型自由发挥', verbose_name='检索优先')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('disabled', '已停用')], default='draft', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('knowledge_bases', models.ManyToManyField(blank=True, related_name='agents', to='knowledge.knowledgebase', verbose_name='关联知识库')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='configs.modelconfig', verbose_name='默认模型')),
            ],
            options={
                'verbose_name': '智能体',
                'verbose_name_plural': '智能体',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='会话标题')),
                ('model_name', models.CharField(blank=True, max_length=128, verbose_name='使用的模型')),
                ('knowledge_base_names', models.JSONField(blank=True, default=list, verbose_name='使用的知识库')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.agent', verbose_name='智能体')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('reasoning', models.TextField(blank=True, verbose_name='思考过程')),
                ('citations', models.JSONField(blank=True, default=list, help_text='[{index, chunk_id, source_name, chapter_path, snippet, score}]', verbose_name='引用来源')),
                ('model_name', models.CharField(blank=True, max_length=128, verbose_name='模型')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入 tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出 tokens')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('is_error', models.BooleanField(default=False, verbose_name='是否出错')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.conversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='agents_conv_updated_f9114a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='agents_mess_convers_0df5a4_idx'),
        ),
    ]
