# Generated by Django 5.2.17 on 2026-09-12 08:41

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models

from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 建 Chunk 表之前必须先有 vector 扩展：向量列与 HNSW 索引都依赖它。
        # 这个操作是 CREATE EXTENSION IF NOT EXISTS，幂等的 ——
        # 早期靠手工 psql 建过扩展的库执行到这里是空操作，不会重复创建。
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='知识库名称')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('chunk_size', models.IntegerField(default=500, verbose_name='切片长度')),
                ('chunk_overlap', models.IntegerField(default=80, verbose_name='切片重叠')),
                ('chunk_strategy', models.CharField(default='heading', max_length=32, verbose_name='切片策略')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases', to='configs.modelconfig', verbose_name='向量模型')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_status', models.CharField(choices=[('pending', '待解析'), ('parsing', '解析中'), ('success', '解析成功'), ('failed', '解析失败')], default='pending', max_length=16, verbose_name='解析状态')),
                ('parse_message', models.TextField(blank=True, verbose_name='解析信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='切片数')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('data_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to='datasets.dataresource', verbose_name='数据资源')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='knowledge.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '知识条目',
                'verbose_name_plural': '知识条目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0, verbose_name='切片编号')),
                ('content', models.TextField(verbose_name='切片内容')),
                ('chapter_path', models.CharField(blank=True, max_length=512, verbose_name='章节路径')),
                ('char_count', models.IntegerField(default=0, verbose_name='字符数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedoc', verbose_name='知识条目')),
            ],
            options={
                'verbose_name': '切片',
                'verbose_name_plural': '切片',
                'ordering': ['knowledge_doc_id', 'seq'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgedoc',
            constraint=models.UniqueConstraint(fields=('knowledge_base', 'data_resource'), name='uniq_kb_resource'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['knowledge_doc', 'seq'], name='knowledge_c_knowled_dae53d_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
