# Generated by Django 5.2.17 on 2026-09-12 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='供应商名称')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='标识')),
                ('base_url', models.CharField(help_text='OpenAI 兼容协议的 base_url', max_length=255, verbose_name='接口地址')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模型供应商',
                'verbose_name_plural': '模型供应商',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=128, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='配置值')),
                ('group', models.CharField(default='general', max_length=64, verbose_name='分组')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='前端下拉里展示的名字', max_length=64, verbose_name='显示名')),
                ('model_id', models.CharField(help_text='调用时传给接口的 model 参数', max_length=128, verbose_name='模型标识')),
                ('kind', models.CharField(choices=[('llm', '大语言模型'), ('embedding', '向量模型'), ('rerank', '重排模型')], default='llm', max_length=16, verbose_name='类型')),
                ('dimension', models.IntegerField(blank=True, help_text='仅向量模型需要', null=True, verbose_name='向量维度')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大输出长度')),
                ('temperature', models.FloatField(default=0.3, verbose_name='温度')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='configs.modelprovider', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'ordering': ['kind', 'sort', 'id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_id', 'kind'), name='uniq_provider_model_kind')],
            },
        ),
    ]
